### ISSUE TITLE
cewolf 1.2-SNAPSHOT dependency

### ISSUE THREAD

**Issue by miku** [smee/elateXam#1]
Just a suggestion for the docs or the README. cewolf 1.2-SNAPSHOT dependency cannot be satisfied by the default maven repositories - so a build of taskmodel would fail. A workaround:

```
$ svn co https://cewolf.svn.sourceforge.net/svnroot/cewolf cewolf

$ cd cewolf/trunk/cewolf

$ ant jar

$ mvn install:install-file -DgroupId=cewolf -DartifactId=cewolf \
    -Dpackaging=jar -Dversion=1.2-SNAPSHOT \
    -Dfile=cewolf-1.1.6.jar -DgeneratePom=true

$ wget -O ~/.m2/repository/cewolf/cewolf/1.2-SNAPSHOT/cewolf-1.2-SNAPSHOT.pom \
    http://ftp.us.xemacs.org/pub/mirrors/maven2/cewolf/cewolf/1.0/cewolf-1.0.pom
```

**Comment by smee** [comment]
Actually I currently use a fork of cewolf that predates the now continued development, you can find it at https://github.com/smee/cewolf
I should adjust to the now released cewolf version, thanks for the reminder.

**Comment by miku** [comment]
I looked everywhere for cewolf, just not in your gh ... ok - works fine now, thanks.
