### ISSUE TITLE
Wrong Class Cast in taskmodel/view/statistics/graph/BoxScoresDatasetProducer.java?

### ISSUE THREAD

**Issue by miku** [smee/elateXam#2]
Is there a wrong cast or signature mismatch in [line 60 of `BoxScoresDatasetProducer`](http://goo.gl/KYy3s)?

```
taskmodel/view/statistics/graph/BoxScoresDatasetProducer.java:[64,27] \
    createBoxAndWhiskerChart(
        java.lang.String,java.lang.String,java.lang.String,
        org.jfree.data.statistics.BoxAndWhiskerXYDataset,boolean) in \
    org.jfree.chart.ChartFactory cannot be applied to   
(java.lang.String,java.lang.String,java.lang.String,
org.jfree.data.statistics.BoxAndWhiskerCategoryDataset,boolean)
```

Whatever the cause was, here's a quick fix: [af3f8cbcebc032af01fde09153de6bb374b912a3](https://github.com/ialt/elateXam/commit/af3f8cbcebc032af01fde09153de6bb374b912a3)

**Comment by smee** [comment]
Please see ticket #1, this should be an issue of using a different version of cewolf.

**Comment by miku** [comment]
Ok, thanks for the instant feedback. Problem solved.
